version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: gt-mongo
    volumes:
      -   gt-mongo-volume:/data/db
    restart: on-failure

  gt-api:
    image: ghcr.io/globex-trading/gt-api:1.0.0
    ports:
      - "3000:3001"
    container_name: gt-api
    depends_on:
      - mongo
    env_file:
      - env/gt-api.env
    volumes:
      - type: bind
        source: ./certs
        target: /certs
        read_only: true
    restart: on-failure

  gt-ws:
    image: ghcr.io/globex-trading/gt-data-fetcher-publisher:1.0.0
    ports:
      - '8080:8080'
    container_name: gt-fetcher-publisher
    depends_on:
      - mongo
      - gt-api
    environment:
      - custom.gt-api.hostname=http://gt-api:3000
      - server.ssl.certificate=/certs/fullchain.pem
      - server.ssl.certificate-private-key=/certs/privkey.pem
    env_file:
      - env/gt-ws.env
    volumes:
      - gt-ws-logs-volume:/logs
      - type: bind
        source: ./certs
        target: /certs
        read_only: true
    restart: on-failure

volumes:
  gt-mongo-volume:
  gt-ws-logs-volume:
