name: Test and Deploy the GT System

on:
  repository_dispatch:
    types: [trigger-test-and-redeploy]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build the Images and Start in Detach Mode
        run: docker-compose up -d

      - name: Pause and Wait 10 Seconds
        run: sleep 10s
        shell: bash

      - name: List all running Containers
        run: docker ps

      - name: View Logs of GT-API
        run: docker logs --tail 1000 --details gt-api

      - name: View Logs of GT-Fetcher-Publisher
        run: docker logs --tail 1000 --details gt-fetcher-publisher

      - name: Stop all Containers and Remove all Images and Volumes
        run: docker-compose down

      - name: Invoke the EC2 restart-with-pull webhook to redeploy the System
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.RESTART_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.RESTART_WEBHOOK_SECRET }}